objectives:
- name: BEVOccupancy
  args:
    weight: 1.32
    bce_weight: 0.9
    range_weighted: True

dataset:
  channels:
    bev:
      name: RawChannel
      indices: lidar
      args:
        sensor: lidar
        channel: rng
        transform:
        - name: Destagger
          args: {}        
        - name: Map2D
          args:
            z_min: -0.3     # Waist/chest height
            z_max: 0.9
            crop_el: 0.4    # Middle 20% (28 beams)
            crop_az: 0.25
