objectives:
- name: Depth
  args:
    weight: 2.19
    loss_order: 1

dataset:
  channels:
    depth:
      name: RawChannel
      indices: lidar
      args:
        sensor: lidar
        channel: rng
        transform:
        - name: Destagger
          args: {}        
        - name: Depth
          args:
            crop_el: 0.0
            crop_az: 0.25
