objectives:
- name: Segmentation
  args:
    weight: 0.208

dataset:
  channels:
    segment:
      name: RawChannel
      indices: camera
      args:
        sensor: _camera
        channel: segment
        transform:
        - name: CameraAugmentations
          args: {}
