outputs:
  occ2d: occ2d

occ2d:
  inputs:
    lidar: lidar
    radar: spectrum
    aug: aug
  output: occ2d
  transform:
    _target_: nrdk.roverd.Occupancy2D
    z_min: -0.3     # Waist/chest height
    z_max: 0.6
    crop_el: 0.4    # Middle 20% (28 beams)
    crop_az: 0.25
