# @package _global_
datamodule:
  dataset:
    sensors:
      pose:
        _partial_: true
        _target_: roverd.sensors.Pose
        reference: radar
        past: 0
        future: 0

transforms:
  sample:
    outputs:
      vel: vel
    vel:
      inputs:
        pose: pose
        aug: aug
      output: vel
      transform:
        _target_: nrdk.roverd.Velocity
