objectives:
- name: BEVOccupancy
  args:
    weight: 1.0
    bce_weight: 0.9
    range_weighted: true
    use_raw_pointclouds: true

dataset:
  channels:
    bev:
      name: RawChannel
      indices: lidar
      args:
        sensor: lidar
        channel: filtered
        transform:
        - name: ColoradarMap2d
          args:
            z_min: -1.0     # Waist/chest height
            z_max: 1.0
            bins: 512
    bev_raw:
      name: RawChannel
      indices: lidar
      args:
        sensor: lidar
        channel: filtered
        transform: []

decoder:
  args:
    # Canonical axes: elevation-azimuth-range
    key: bev
    pos_scale: [1.0, 1.0, 1.0]
    shape: [1, 512, 128]
    patch: [1, 16, 16]
