objectives:
- name: Segmentation
  args:
    weight: 1.0

dataset:
  channels:
    segment:
      name: RawChannel
      indices: camera
      args:
        sensor: _camera
        channel: segment
        transform:
        - name: CameraAugmentations
          args: {}

decoder:
  args:
    # Canonical axes: elevation-azimuth-range
    # 120 deg / 180 deg azimuth crop; no elevation crop
    key: segment
    pos_scale: [1.0, 0.666, 1.0]
    shape: [160, 160, 1]
    patch: [5, 5, 1]
