objectives:
- name: Velocity
  args:
    weight: 1.0
    loss_order: 2

dataset:
  channels:
    vel:
      name: "NPChannel"
      indices: lidar
      args:
        path: "_lidar/pose.npz"
        keys: ["vel", "rot"]
        transform:
        - name: RelativeVelocity
          args: {}

# Override all args since this isn't a standard transform layer
:decoder:
  name: VectorDecoder
  args:
    key: vel
    layers: [512, 512, 512]
    dropout: 0.1
    activation: GELU
    out_dim: 4
