site_name: Neural Radar Development Kit
repo_url: https://github.com/RadarML/nrdk
repo_name: RadarML/nrdk
nav:
  - nrdk:
    - Overview: index.md
    - Architecture: design.md
    - Core Modules:
      - nrdk.config: nrdk/config.md
      - nrdk.framework: nrdk/framework.md
      - nrdk.metrics: nrdk/metrics.md
      - nrdk.modules: nrdk/modules.md
      - nrdk.objectives: nrdk/objectives.md
      - nrdk.roverd: nrdk/roverd.md
      - nrdk.vis: nrdk/vis.md
    - CLI Tools: cli.md
  - nrdk.tss:
    - Overview: tss/index.md
    - High Level API: tss/api.md
    - Stats: tss/stats.md
    - Utils: tss/utils.md
  - nrdk.models: models.md
  - grt:
    - Overview: grt/index.md
    - Models: grt/models.md


extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: octicons/ai-model-16
    annotation: material/arrow-right-circle
  font:
    code: monospace
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: green
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: green
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to system preference


plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        paths:
        - src
        - grt
        options:
          docstring_style: google
          relative_crossrefs: true
          separate_signature: true
          line_length: 80
          show_signature_annotations: true
          signature_crossrefs: true
          show_root_full_path: true
          show_root_members_full_path: true
          show_symbol_type_heading: true
          show_root_heading: true
          show_root_toc_entry: true
          heading_level: 1
          check_crossrefs_exclude:
          - "^torch\\.(.*)"
          - "^numpy\\.(.*)"
          - "^lightning\\.(.*)"
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://docs.pytorch.org/docs/stable/objects.inv
        - https://docs.jax.dev/en/latest/objects.inv
        - https://radarml.github.io/abstract-dataloader/objects.inv
        - https://radarml.github.io/xwr/objects.inv
        - https://radarml.github.io/red-rover/objects.inv
        - https://lightning.ai/docs/pytorch/stable/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.snippets
