<<: !include ../objectives/bev.yaml

decoders:
- name: Transformer2DDecoder
  args:
    key: bev
    layers: 3
    ff_ratio: 4.0
    heads: 8
    dropout: 0.1
    activation: GELU
    shape: [1024, 256]
    patch: [32, 16]
    positions: nd
