objectives: []

encoder:
  name: TransformerEncoder
  args:
    # From size spec: layers, dim
    ff_ratio: 4.0
    dropout: 0.1
    head_dim: 64
    activation: GELU
    patch: [8, 1, 1, 16]
    pos_scale: [1.0, 1.0, 1.0, 1.0]
    global_scale: 16.0
    input_channels: 2
    positions: nd

decoder:
  name: TransformerDecoder
  args:
    # From size spec: layers, dim
    # From objective spec: key, shape, patch, pos_scale
    ff_ratio: 4.0
    head_dim: 64
    dropout: 0.1
    global_scale: 16.0
    activation: GELU
    positions: nd

optimizer:
  name: AdamW
  default_lr: 0.0001
  warmup: 100
  subsets: {}

dataset:
  batch_size: 32
  val_samples: 16
  channels:
    radar:
      name: RawChannel
      indices: radar
      args:
        sensor: radar
        channel: iq
        transform:
        - name: AssertTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
        - name: FFTArray
          args:
            pad: 0
            axes: [0, 1, 2, 3]
        - name: ComplexPhase
          args: {}
