<<: !include ../objectives/segment.yaml

decoders:
- name: Transformer2DDecoder
  args:
    key: segment
    layers: 2
    ff_ratio: 4.0
    head_dim: 64
    dropout: 0.1
    activation: GELU
    shape: [160, 160]
    patch: [8, 8]
    out_dim: 8
    positions: nd
