objectives: []

encoder:
  name: AxialEncoder
  args:
    ff_ratio: 4.0
    dropout: 0.1
    activation: GELU
    patch: [8, 1, 1, 16]
    size: [64, 8, 2, 256]
    windows: [[8, 8, 1, 1], [1, 1, 2, 16]]
    positions: nd
    layers: 9
    dim: 512
    heads: 8

decoders: []

optimizer:
  name: AdamW
  default_lr: 0.0001
  warmup: 100
  subsets: {}

dataset:
  batch_size: 32
  val_samples: 16
  channels:
    radar:
      name: RawChannel
      indices: radar
      args:
        sensor: radar
        channel: iq
        transform:
        - name: AssertTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
        - name: FFTArray
          args:
            pad: 0
            axes: [0, 1, 2, 3]
        - name: ComplexPhase
          args: {}
