# @package _global_
datamodule:
  traces:
    train:
      indoor:
        baker: [
          "baker.1.fwd", "baker.1.lat", "baker.2.fwd", "baker.2.lat"]
        cic: [
          "cic.1.fwd", "cic.1.lat", "cic.2.fwd", "cic.2.lat", "cic.4.fwd",
          "cic.4.lat"]
        doherty: [
          "doherty.1.fwd", "doherty.1.lat", "doherty.a.fwd", "doherty.a.lat",
          "doherty.b.fwd", "doherty.b.lat"]
        gates: [
          "gates.3.fwd", "gates.3.lat", "gates.4.fwd", "gates.4.lat",
          "gates.5.fwd", "gates.5.lat", "gates.6.fwd", "gates.6.lat",
          "gates.7.fwd", "gates.7.lat"]
        hamburg: [
          "hamburg.1.fwd", "hamburg.1.lat", "hamburg.2.fwd", "hamburg.2.lat",
          "hamburg.3.fwd", "hamburg.3.lat", "hamburg.a.fwd", "hamburg.a.lat"]
        hunt: [
          "hunt.1.fwd", "hunt.1.lat", "hunt.2.fwd", "hunt.2.lat", "hunt.3.fwd",
          "hunt.3.lat"]
        nsh: [
          "nsh.1.fwd", "nsh.1.lat", "nsh.2.fwd", "nsh.2.lat", "nsh.3.fwd",
          "nsh.3.lat", "nsh.4.fwd", "nsh.4.lat"]
        porter: [
          "porter.1.fwd", "porter.1.lat", "porter.2.fwd", "porter.2.lat",
          "porter.a.fwd", "porter.a.lat"]
        roberts: [
          "roberts.1.fwd", "roberts.1.lat", "roberts.2.fwd", "roberts.2.lat",
          "roberts.3.fwd", "roberts.3.lat", "roberts.4.fwd", "roberts.4.lat"]
        scaife: [
          "scaife.1.fwd", "scaife.1.lat", "scaife.3.fwd", "scaife.3.lat"]
        scott: [
          "scott.3.fwd", "scott.3.lat", "scott.4.fwd", "scott.4.lat",
          "scott.5.fwd", "scott.5.lat", "scott.6.fwd", "scott.6.lat"]
        tepper: [
          "tepper.1.fwd", "tepper.1.lat", "tepper.2.fwd", "tepper.2.lat",
          "tepper.3.fwd", "tepper.3.lat", "tepper.4.fwd", "tepper.4.lat",
          "tepper.5.fwd", "tepper.5.lat"]
        uc: [
          "uc.1.fwd", "uc.1.lat", "uc.2.fwd", "uc.2.lat", "uc.3.fwd", "uc.3.lat",
          "uc.ll.fwd", "uc.ll.lat"]
        wean: [
          "wean.3.fwd", "wean.3.lat", "wean.4.fwd", "wean.4.lat", "wean.5.fwd",
          "wean.5.lat", "wean.6.fwd", "wean.6.lat"]
