_target_: grt.models.SpectrumTokenizer
d_model: ${size.d_model}
patch: [1, 2, 2, 8, 4]  # (time, doppler, elevation, azimuth, range)
squeeze: [2, 3]  # elevation + azimuth
n_channels: 3 
scale: [1.0, 1.0, 1.0]
w_min: 0.2
positions: nd
