<<: !include ../objectives/bev.yaml

decoders:
- name: SwinDPT2DDecoder
  args:
    key: bev
    head_dim: 64
    stages: 4
    dropout: 0.1
    activation: GELU
    shape: [1024, 256]
    patch: [8, 4]
