<<: !include ../objectives/bev.yaml

decoders:
- name: SwinDPT2DDecoder
  args:
    key: bev
    skip_factor: 2
    head_dim: 64
    stages: 3
    dropout: 0.1
    activation: GELU
    shape: [1024, 256]
    patch: [8, 4]
    out_dim: 0
    conv_type: separable
