objectives: []

encoder:
  name: SwinTransformerEncoder
  args:
    stages:
    - merge: [2, 1, 1, 2]
      blocks: 2
      window: [4, 4, 2, 4]
      shift: [2, 2, 0, 2]
    - merge: [2, 1, 1, 2]
      blocks: 2
      window: [4, 4, 2, 4]
      shift: [2, 2, 0, 2]
    - merge: [2, 1, 1, 2]
      blocks: 2
      window: [4, 4, 2, 4]
      shift: [2, 2, 0, 2]
    fa_layers: 2
    dim: 128
    head_dim: 64
    ff_ratio: 4.0
    dropout: 0.1
    activation: GELU
    patch: [4, 1, 1, 8]

decoders: []

optimizer:
  name: AdamW
  default_lr: 0.0001
  warmup: 100
  subsets: {}

dataset:
  batch_size: 32
  channels:
    radar:
      name: RawChannel
      indices: radar
      args:
        sensor: radar
        channel: iq
        transform:
        - name: AssertTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
        - name: FFTArray
          args:
            pad: 0
            axes: [0, 1, 2, 3]
        - name: ComplexPhase
          args: {}
