objectives:
- name: BEVOccupancy
  args:
    weight: 1.0
    bce_weight: 0.9
    range_weighted: True

encoder:
  name: UNetEncoder
  args:
    n_doppler: 64
    dim: 64

decoder:
  name: UNetBEVDecoder
  args:
    key: bev

dataset:
  batch_size: 32
  val_samples: 16
  channels:
    radar:
      name: RawChannel
      indices: radar
      args:
        sensor: radar
        channel: iq
        transform:
        - name: DiscardTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
        - name: FFTLinear
          args:
            pad: 56
            axes: [1, 2]
        - name: ComplexAmplitude
          args:
            keepdim: false
    bev:
      name: RawChannel
      indices: lidar
      args:
        sensor: lidar
        channel: rng
        transform:
        - name: Destagger
          args: {}        
        - name: Map2D
          args:
            z_min: -0.3     # Waist/chest height
            z_max: 0.6
            crop_el: 0.4    # Middle 20% (28 beams)
            crop_az: 0.25
