# @package _global_
datamodule:
  dataset:
    sensors:
      lidar:
        _partial_: true
        _target_: roverd.sensors.OSLidar
        correction: auto
        past: 0
        future: 0

  datamodule:
    transforms:
      sample:
        outputs:
          occ3d: occ3d
        occ3d:
          inputs:
            lidar: lidar
            radar: spectrum
            aug: aug
          output: occ3d
          transform:
            _target_: nrdk.roverd.LidarOccupancy3D
            crop_az: 0.25
            decimate: [2, 8, 4]
