# Amplitude only
dataset:
  channels:
    radar:
      args:
        :transform:
        - name: AssertTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
        - name: FFTArray
          args:
            pad: 0
            axes: [0, 1, 2, 3]
        - name: ComplexAmplitude
          args: {}

# Need to specify only one input channel
encoder:
  args:
    input_channels: 1
