traces: [
  "cic/cic.1.fwd", "cic/cic.1.lat", "cic/cic.2.fwd", "cic/cic.2.lat",
  "cic/cic.4.fwd", "cic/cic.4.lat",
  "hamburg/hamburg.1.fwd", "hamburg/hamburg.1.lat", "hamburg/hamburg.2.fwd",
  "hamburg/hamburg.2.lat", "hamburg/hamburg.3.fwd", "hamburg/hamburg.3.lat",
  "hamburg/hamburg.a.fwd", "hamburg/hamburg.a.lat"
]
val_samples: [1000, 2000, 3000, 4000, 5000, 6000]
pval: 0.2
