traces:
- carnival1
- carnival2
- cfa
- cic1
- cic2
- doherty
- ghc
- hamburg
- hammerschlag
- hunt
- morrison
- porter
- posner
- scott
- tepper
- uc
- wean
val_samples: [2000, 4000, 6000, 8000, 10000, 12000]
pval: 0.2
