objective: RadarHD
model: RadarTransformer
model_args:
  dim: 512
  ff_ratio: 4.0
  heads: 8
  dropout: 0.1
  activation: GELU
  in_shape: [64, 256, 8, 2]
  out_shape: [1024, 256]
optimizer: AdamW
optimizer_args: {}
default_lr: 0.001
bce_weight: 0.9
dataset:
  batch_size: 16
  train:
  - carnival1
  - carnival2
  - cic1
  - cic2
  - ghc
  - hamburg
  - hammerschlag
  - porter
  - scaife
  - scott
  - tepper
  - wean
  val:
  - cic4
  - nsh
  - smith
  transform:
    lidar:
    - args: {}
      name: Destagger
    - args: {}
      name: Map2D
    radar:
    - args: {}
      name: DiscardTx2
    - args: {}
      name: IIQQtoIQ
    - args:
        pad: 0
        axes: [0, 1, 2]
      name: FFTLinear
    - args: {}
      name: ComplexPhase
