objective: RadarHD
model: RadarUNet
model_args:
  d_input: 64
  doppler: False
optimizer: AdamW
optimizer_args: {}
default_lr: 0.001
bce_weight: 0.9
range_weighted: True
dataset:
  <<: !include _traces.yaml
  batch_size: 16
  transform:
    lidar: !include _lidar-map.yaml
    radar:
    - args: {}
      name: DiscardTx2
    - args: {}
      name: IIQQtoIQ
