objective: RadarHD3D
model: RadarTransformer
model_args:
  enc_layers: 5
  dec_layers: [5, 3, 1]
  dim: 512
  ff_ratio: 4.0
  heads: 8
  dropout: 0.1
  activation: GELU
  out_shape: [128, 1024]
  patch_size: [16, 16]
  unpatch_size: [16, 16]
optimizer: AdamW
optimizer_args: {}
warmup: 100
default_lr: 0.0001
loss_order: 1
dataset:
  <<: !include _traces.yaml
  batch_size: 32
  transform:
    lidar:
    - args: {}
      name: Destagger
    - args:
        crop_el: 0.0
        crop_az: 0.25
      name: Depth
    radar: !include _radar-fft-full.yaml
