objectives: []

encoder:
  name: UNeXTEncoder
  args:
    dim: 64
    d_input: 64
    depth: 3
    doppler: True

decoders: []

optimizer:
  name: AdamW
  default_lr: 0.0001
  warmup: 100
  subsets: {}

dataset:
  batch_size: 16
  channels:
    radar:
      name: RawChannel
      indices: radar
      args:
        sensor: radar
        channel: iq
        transform:
        - name: DiscardTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
