objectives: []

encoder:
  name: UNetEncoder
  args:
    pad: 64
    n_azimuth: 8
    dim: 64
    doppler: True

decoders: []

optimizer:
  name: AdamW
  default_lr: 0.0001
  warmup: 100
  subsets: {}

dataset:
  batch_size: 32
  channels:
    radar:
      name: RawChannel
      indices: radar
      args:
        sensor: radar
        channel: iq
        transform:
        - name: DiscardTx2
          args: {}
        - name: IIQQtoIQ
          args:
            scale: 0.001
