dataset:
  traces: !expand
    coloradar:
      - 2_22_2021_longboard_run3
      - 2_22_2021_longboard_run4
      - 2_22_2021_longboard_run6
      - 2_22_2021_longboard_run7
      - 2_24_2021_aspen_run3
      - 2_24_2021_aspen_run4
      - 2_24_2021_aspen_run5
      - 2_24_2021_aspen_run6
      - 2_24_2021_aspen_run7
      - 2_24_2021_aspen_run8
      - 2_24_2021_aspen_run9
      - 2_24_2021_aspen_run10
      - 2_24_2021_aspen_run11
      - 2_28_2021_outdoors_run3
      - 2_28_2021_outdoors_run4
      - 2_28_2021_outdoors_run5
      - 2_28_2021_outdoors_run6
      - 2_28_2021_outdoors_run7
      - 2_28_2021_outdoors_run8
      - 2_28_2021_outdoors_run9
      - 12_21_2020_arpg_lab_run3
      - 12_21_2020_arpg_lab_run4
      - 12_21_2020_ec_hallways_run3
      - 12_21_2020_ec_hallways_run4
      - 2_23_2021_edgar_classroom_run3
      - 2_23_2021_edgar_classroom_run4
      - 2_23_2021_edgar_classroom_run5
      - 2_23_2021_edgar_army_run3
      - 2_23_2021_edgar_army_run4
      - 2_23_2021_edgar_army_run5
