# Evaluation traces
traces: !expand
  indoor:
    cfa: [
      "cfa.1.fwd", "cfa.1.lat", "cfa.3.fwd", "cfa.3.lat", "cfa.a.fwd",
      "cfa.a.lat"]
    morrison: [
      "morrison.1.fwd", "morrison.1.lat", "morrison.2.fwd", "morrison.2.lat"]
    posner: [
      "posner.1.fwd", "posner.1.lat", "posner.2.fwd", "posner.2.lat",
      "posner.3.fwd", "posner.3.lat", "posner.a.fwd", "posner.a.lat"]
