name: Run CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Fetch secrets
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
                ${{ secrets.XWR_PRIVATE_KEY }}
                ${{ secrets.RED_ROVER_PRIVATE_KEY }}

    - name: Install uv with Python 3.12
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.12"

    - name: Lint with ruff
      run: |
        uv run --extra dev ruff check ./src

    - name: Type check with pyright
      run: |
        uv run --extra dev --extra roverd pyright ./src

    - name: Run tests
      run: |
        uv run --extra dev --extra roverd -ra -- tests
